
TICKER_MAP = {
    'CCO CN': 'CCO.TO',
    'NXE CN': 'NXE.TO',
    'DML CN': 'DML.TO',
    'EFR CN': 'EFR.TO',
    'ARE CN': 'ARE.TO',
    'GLO CN': 'GLO.TO',
    'FCU CN': 'FCU.TO',
    'EU CN': 'EU.V',
    'URC CN': 'URC.V',
    'ISO CN': 'ISO.V',
    'UEX CN': 'UEX.TO',
    'GXU CN': 'GXU.V',
    'AZZ CN': 'AZZ.TO',
    'LAM CN': 'LAM.TO',
    'WUC CN': 'WUC.CN',
    'FSY CN': 'FSY.TO',
    'PDN AU': 'PDN.AX',
    'MQG AU': 'MQG.AX',
    'BOE AU': 'BOE.AX',
    'DYL AU': 'DYL.AX',
    'BMN AU': 'BMN.AX',
    'PEN AU': 'PEN.AX',
    'VMY AU': 'VMY.AX',
    'LOT AU': 'LOT.AX',
    'GGG AU': 'GGG.AX',
    'YCA LN': 'YCA.L',
    'RIO LN': 'RIO.L',
    'BHP LN': 'BHP.L',
    '8053 JP': '8053.T',
    '8001 JP': '8001.T',
    '7011 JP': '7011.T',
    '006360 KS': '006360.KS',
    '047040 KS': '047040.KS',
    '028260 KS': '028260.KS',
    '000720 KS': '000720.KS',
    '034020 KS': '034020.KS',
    '1816 HK': '1816.HK',
    '1164 HK': '1164.HK',
    'UEC': 'UEC',
    'LEU': 'LEU',
    'URG': 'URG',
    'BKY SM': 'BKY.MC',
    'KAP LI': 'KAP.IL',
    'SSW SJ': 'SSW.JO',
    'CENTRUS ENERGY CORP .': 'LEU',
    'DENISON MINES CORP .': 'DNN',
    'CAMECO CORP .': 'CCJ',
    'LARAMIDE RESOURCES LTD .': 'LAM.TO',
    'FORSYS METALS CORPORATION .': 'FSY.TO',
    'MEGA URANIUM LTD .': '',
    'UEX CORP .': 'UEX.TO',
    'NAC KAZATOMPROM JSC GDR': 'KAP.IL',
    'DEEP YELLOW LTD .': 'DYL.AX',
    'PENINSULA ENERGY LTD .': 'PEN.AX',
    'BERKELEY ENERGIA LTD .': 'BKY.L',
    'PALADIN ENERGY LTD': 'PDN.AX',
    'UR-ENERGY INC .': 'URG',
    'URANIUM ENERGY CORP .': 'UEC',
    'BANNERMAN ENERGY LTD .': 'BMN.AX',
    'TORO ENERGY LTD .': 'TOE.AX',
    'BOSS ENERGY LTD .': 'BOE.AX',
    'CGN MINING CO LTD HK/01164': '1164.HK',
    'FISSION URANIUM CORP .': 'FCU.TO',
    'NEXGEN ENERGY LTD .': 'NXE',
    'ISOENERGY LTD .': 'ISO.V',
    'GLOBAL ATOMIC CORP .': 'GLO.TO',
    'YELLOW CAKE PLC .': 'YCA.L',
    'ENERGY FUELS INC NEW': 'UUUU',
    'LOTUS RESOURCES LTD .': 'LOT.AX',
    'GOVIEX URANIUM INC CL A': 'GXU.V',
    'ENCORE ENERGY CORP .': 'EU.V',
    'AZARGA URANIUM CORP CL A': 'AZZ.TO',
    'VIMY RESOURCES LTD .': 'VMY.AX',
    'HONG KONG DOLLAR ': 'HKDUSD=X',
}
